apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-service
  namespace: deployment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-service
  template:
    metadata:
      labels:
        app: deployment-service
    spec:
      serviceAccountName: deployer-sa
      containers:
        - name: deployment-service
          image: k8s-deployment-service:v001
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-service
  namespace: deployment-service
spec:
  selector:
    app: deployment-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer-sa
  namespace: deployment-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployer-role
  namespace: deployment-service
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-rolebinding
  namespace: deployment-service
subjects:
  - kind: ServiceAccount
    name: deployer-sa
    namespace: deployment-service
roleRef:
  kind: Role
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io
